spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      authentication-database: admin
      database: detector-api
      port: 27017
#      host: localhost
#    datasource:
#      url: jdbc://localhost:27017/detector-api
logging:
  level:
    org:
      springframework: ERROR