spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      authentication-database: admin
      database: detector-api
      port: 27017
logging:
  level:
    org:
      springframework: ERROR